### PR TITLE
Potential fix for https://github.com/openfl/extension-iap/issues/34.

### PR DESCRIPTION
**Pull request by thomasuster**
The intent of this fix is to check when the IAPService has been disconnected after initial connection. For each of the IabHelper's use of the mService variable, my intent is to perform the fail case for each function if the IAPService is disconnected ``(mService == null)```. So this IAP operation should fail, the app handles the fail normally, and then hopefully at some point if the service gets reconnected and if the user tried an IAP operation again it should work normally.

### CODE REVIEW

**Comment by thomasuster** [comment]
If @fbricker or @bryanchacosky wants to take a look and see if the diff looks okay I'd appreciate it. I also tested it with Pakka pets for multiple IAPs, everything worked as expected. I don't know how to test when the service disconnect, so that will only work if my logic is sound.

**Comment by thomasuster** [comment]
Travis seems to be something to do with hxcpp. Should I make a PR selecting a stable hxcpp version?

```/Users/travis/lime/lime/text/Font.hx:166: characters 15-29 : haxe.io.Bytes has no field getInt32```

**Comment by thomasuster** [comment]
@jgranick Any idea why CI is failing?

**Comment by jgranick** [comment]
Perhaps the CI uses Haxe 3.1 instead of 3.2?

**Comment by fbricker** [comment]
Hi, the diff looks nice to me. I suggest we merge this :+1:

**Pull request merged**
